// INCLUDE FILE generated by "Pelles C for Windows, version 1.00".

#define DLG_MAIN  1001
#define IDR_ICO_MAIN  8001
#define IDFTEST  4001
#define IDEXIT  4002
#define IDLIST1  4003
#define IDPSYS  1
#define IDPMEM  4004
#define IDPCUSTOM  4005
